### PR TITLE
Change targeted dialog position via state, remove arrow of color picker when place above target

### PR DESCRIPTION
**Pull request by designedbyscience**
While attempting to work on #2560, I changed the targeted positioning of the dialogs to happen via state changes rather than the direct changing of properties

IT SEEMS TO WORK FINE. But that statement is a little worrisome, so more eyes/click to check would be better.

Also, that little arrow on the color picker goes away when it is placed above the target element

### CODE REVIEW

**Comment by placegraphichere** [comment]
Wondering if we can do the arrow on the bottom? here's what I mocked up:

*dialog.less*
`.dialog-pointer-bottom(@left) {
    content: "";
    position: absolute;
    top: auto;
    bottom: -0.9rem;
    left: @left;
    width: 1.5rem;
    height: 1.5rem;
    background: @bg-border;
    border: none;
    border-left: @hairline*1.5 solid @underlines;
    border-top: @hairline*1.5 solid @underlines;
    border-top-left-radius: 0.2rem;
    transform: rotate(225deg);
    -webkit-clip-path: polygon(0% 0%, 1.8rem 0%, 0% 1.8rem);
}`

*color-picker.less*
`&.placed-above:before {
    .dialog-pointer-bottom(1.6rem);
}`

screen shot 2015-10-21 at 6 23 14 pm

**Comment by iwehrman** [comment]
I can't rationally see why your member/state change wouldn't work. But, also, the arrow elision doesn't seem to be working for me:
ar

**Comment by placegraphichere** [comment]
Ahhh, that's probably why we shouldn't add it to the bottom. I think @designedbyscience is just adjusting for any variation that doesn't allow it to sit in its natural state.

**Comment by designedbyscience** [comment]
Okay, now arrow disappears for both "out of natural state" conditions

**Comment by iwehrman** [comment]
:hamburger: :fries:

**Pull request merged**
