### PR TITLE
On no-selection, don't shift zoom center.

### PR DESCRIPTION
**Pull request by volfied**
If there is no selection during zoom in/out, we keep the center fixed and zoom out/in correctly.

Addresses #661, and possibly couple other zoom bugs that I will add as I see them.
#2206
#2169
#1081
#1709
@iwehrman You sic'ed me on this, you review it :)

### CODE REVIEW

**Comment by volfied** [comment]
With 889fc9c, also addresses #2206

**Comment by volfied** [comment]
Also addresses #2169

**Comment by volfied** [comment]
Also addresses #1081

**Comment by volfied** [comment]
Also addresses #1709

**Comment by iwehrman** [comment]
:moneybag: :moneybag: :moneybag:

**Comment by iwehrman** [comment]
This doesn't quite fix #1081 because of the manual re-positioning that we're doing. This is related to #1999. Imma gonna fix that by just ripping out our re-centering code, since that should no longer be necessary given that our overlay offsets are fixed.

**Pull request merged**
