### PR TITLE
Commit color picker values on tab/enter fix

### PR DESCRIPTION
**Pull request by hamburge**

### CODE REVIEW

**Comment by iwehrman** [comment]
Does this have any other ramifications? I think you removed that if statement originally? Or am I confused?

**Comment by iwehrman** [comment]
Also, is this for #1754?

**Comment by chadrolfs** [comment]
first glance: fix looks good.
one thing that should also be fixed is after you type into the field and hit return it should apply AND select-all in the field (see other field behavior to compare).

**Comment by chadrolfs** [comment]
@iwehrman yes, this is a fix for that.

**Comment by hamburge** [comment]
Yes, #1754.

Originally I took out a call to _commit, which was bad. Then to fix that I undid it and added in `this.props.onChange(event, nextValue);` after `event.stopPropagation()` That broke layer renaming, so I added in the condition (53c1b). I don't really know why it works now (and doesn't break layer renaming)-- did someone change how that works?

**Comment by hamburge** [comment]
@chadrolfs @iwehrman Fixed the highlighting as well!

**Comment by chadrolfs** [comment]
yay!  :facepunch:

**Comment by hamburge** [comment]
@chadrolfs @iwehrman Gah wait now I remember why that condition is in there. Without it, clicking on options in layer search only sometimes works.

**Comment by chadrolfs** [comment]
d'oh!

**Comment by hamburge** [comment]
OK I think this should be better. I removed the condition on if a TextInput is live in `_commit`, which was added as a fix for a bug in search a while back (#1563). That should fix the color picker. Then I dealt with the search bug for real in Datalist instead.

**Comment by iwehrman** [comment]
Man you dealt with that bug _for real_. :bug: :gun:

**Pull request merged**
