### PR TITLE
Handle case where first guide is added to a new document

### PR DESCRIPTION
**Pull request by mcilroyc**
This addresses #3276.  A new document will not have "guides" property (due to recent lazy loading change), so this handles that case when setting the first guide.  @iwehrman please review to make sure this is inline with how we should recover from lazy loading of guides.

### CODE REVIEW

**Comment by iwehrman** [comment]
It's unclear why this is happening before guides are initialized. That is, I don't understand why we're running code to clear or set guides when guides are disabled. Or, are we not doing that, and guide initialization is broken in a different way?

**Comment by mcilroyc** [comment]
Guides are not initialized for new documents.  `allocateDocument` calls `updateDocument` which handles non-current documents as though they have guides visibility false
https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/documents.js#L416

**Comment by iwehrman** [comment]
To re-state our offline conversation for posterity: I think that is the bug that should be fixed. I intentionally did not add this check in my original PR because I assumed that it should not be necessary given the invariant that guides are initialized IFF guides have been set visible at least once.

**Comment by mcilroyc** [comment]
Take two,  @iwehrman.  reverted the first attempt in favor of a change to allocateDocument which forces the document to be updated in "current" mode.  This properly initializes guides.

**Comment by iwehrman** [comment]
It's a bummer that this probably adds a small delay, but probably only very small. At some point we might also want to make the parameter conventions for `updateDocument` a little less weird. Anywho, looks good.

**Pull request merged**
