### PR TITLE
initial spectrum matching to classic

### PR DESCRIPTION
**Pull request by placegraphichere**
Dave and I to review, involving spectrum color stop changes to sync with classic

- artboard collapsed icon fix
- document-header border/box-shadows for app bar and canvas
- toolbar border/box-shadows for app bar and canvas
- panels border/box-shadows for app bar and canvas
- colors for underlines and text for disabled
- margins at 1.6rem
- icon and item color differentiation in colors
- text color set to inactive instead of disabled

fixed: 
- blurred ends on input fields fixed
- tools selected state fixed
- unpinned toolbar height fixedf
- fixed no-doc state and panel the being different widths

### CODE REVIEW

**Comment by iwehrman** [comment]
The border between the title bar and the panels is a different width compared to the inter-panel borders:
image

**Comment by iwehrman** [comment]
The "suffix" text inputs seem to have a different color underlines from the other input underlines:
image

**Comment by placegraphichere** [comment]
The suffix thing is a known issue that cory is looking at. It has a disabled state for some reason

**Comment by davealonzo** [comment]
the suffix input also appears to be slightly misaligned hight than the other row items

**Comment by davealonzo** [comment]
Layers panel (when collapsed) doesn't align with alignment tools or document header bar.

screen shot 2015-09-16 at 11 10 11 am

**Comment by davealonzo** [comment]
Space between panel icons (e.g. export, add, copy, etc.) is inconsistent across the various sub sections.

screen shot 2015-09-16 at 11 11 31 am

**Comment by davealonzo** [comment]
Rename/create new library state:
  - UI doesn’t extend to right panel margin
  - Missing secondary button title color (for "Cancel")

screen shot 2015-09-16 at 11 10 50 am

**Comment by iwehrman** [comment]
Is PS sticking with the nearly black no-doc background color? It feels a slightly weird to me with the border color. But, maybe I'll get used to it:
image

**Comment by davealonzo** [comment]
@iwehrman I don't think so but need to verify the default matte color for this color stop so that our border colors are more seamless - at least when there's a doc open.

**Comment by placegraphichere** [comment]
@davealonzo the library width issue is being resolved on my other pull request #2429

**Comment by davealonzo** [comment]
Just verified... the default matte bg color for this color stop will be #191919 (rgb 25, 25, 25). It will be the same for the no-doc state as well.

**Comment by davealonzo** [comment]
Suffix data list looks off:
- underscore riding a little too high compared to the data lists
- underscore edges are a little distorted

export_datalists

**Comment by placegraphichere** [comment]
Feedback addressed. 

@iwehrman can you reassign or review ?

**Comment by designedbyscience** [comment]
I'd like to take a pass over this stuff as well... (will do today)

**Comment by iwehrman** [comment]
The title bar border is still smaller than the other borders:
image

**Comment by iwehrman** [comment]
It seems that toolbar icons no longer have any selected state:
image

**Comment by iwehrman** [comment]
Unpinned toolbar:
image

**Comment by iwehrman** [comment]
For technical reasons, we really want the no-doc column to be exactly the same width as the columns in the properties panel:
image

**Comment by davealonzo** [comment]
The underscores of the data lists line up now, but the ends are a little fuzzy. Here's a blow up.

screen shot 2015-09-18 at 9 47 00 am

**Comment by iwehrman** [comment]
Perhaps not a crisis, but the alignment of the left edge of the labels with the right edge of the inputs feels weird to me here:
image

5___Blur 5___Spread 5___

**Comment by iwehrman** [comment]
Over to @designedbyscience so that he can get a few licks in too.

**Comment by placegraphichere** [comment]
Ahh damn it @davealonzo, I thought I addressed that. I will fix

**Comment by davealonzo** [comment]
@placegraphichere that's cool, had to throw my glasses on to pick up on it

**Comment by designedbyscience** [comment]
I like it Dave!

**Comment by iwehrman** [comment]
Now that @davealonzo pointed one out, I'm finding those fuzzy underline endpoints everywhere! 
image
:bug: :beetle: :ant:

**Comment by placegraphichere** [comment]
Fixes should be complete, @iwehrman I'm not doing the top app bar border-width issue, I will address that with @davealonzo separately. 

Otherwise back to @designedbyscience for review/reassignment

**Comment by iwehrman** [comment]
It's looking absolutely fantastic! The top-bar border issue is fine to delay, but I still see borders of different widths in the rest of the UI:
image
I'm using a retina MBP at the default resolution (1440x900 effective).

**Comment by iwehrman** [comment]
Like a rock!
image

**Comment by iwehrman** [comment]
This is probably crazy, but maybe there should be an outer border too?
image

**Comment by iwehrman** [comment]
Looks like the toolbar icons lost their "active" state:
image

**Comment by davealonzo** [comment]
Wrt different border widths, the thicker of the two was originally intended for distinguishing one primary panel section from another (title bars, toolbars, column panels), while the thinner was intended for separating sub sections within a primary panel (transform, appearance, layers, libraries, etc.).

**Comment by iwehrman** [comment]
@davealonzo @placegraphichere: The differing border widths definitely feel wrong to me. But I guess that's just, like, my opinion.

**Comment by iwehrman** [comment]
Also note that the borders _are_ a consistent width on non-retina displays:
image

**Comment by placegraphichere** [comment]
- unified hover/active states for icon css for toolbar and panel tabs 
- fixed inconsistent borders
- fixed/unified border widths that don't show on certain retina resolutions
- added border on app frame

@iwehrman back to you I think

**Comment by iwehrman** [comment]
One more bug: the toolbar icon disappears when the toolbar is unpinned:
image

**Comment by iwehrman** [comment]
One more:
img

**Comment by placegraphichere** [comment]
lets try again @iwehrman

**Comment by iwehrman** [comment]
Bombs away!

**Pull request merged**
