### PR TITLE
Took away the blue hover on disabled inputs

### PR DESCRIPTION
**Pull request by DivyaPrabhakar**
Signifies they are not active
Regarding #1462

### CODE REVIEW

**Comment by iwehrman** [comment]
Seems great, but I wonder if this addresses a particular issue? Hmmm...

**Comment by DivyaPrabhakar** [comment]
😅

**Comment by iwehrman** [comment]
Ah, #1462. I must have overlooked that! Anyway, the fix looks great. Thanks!

**Comment by DivyaPrabhakar** [comment]
You are so irresponsible Ian.

**Pull request merged**
