### PR TITLE
Ref point center and X, Y set to zero now displays

### PR DESCRIPTION
**Pull request by DivyaPrabhakar**
References issue #3350

### CODE REVIEW

**Comment by mcilroyc** [comment]
This seems like a significant change to a commonly used utility (pluck).  I'm not sure this is safe.  Pardon me if you've already cleared this with @iwehrman or something along those lines.

**Comment by mcilroyc** [comment]
I'm going to compare this with lodash's pluck, and then I'll stop griping and merge it

**Comment by DivyaPrabhakar** [comment]
@mcilroyc I have not cleared it with anyone so the scrutiny is welcome

**Comment by mcilroyc** [comment]
Ok, I now believe this is safe.  Part of my misunderstanding was the particular case that this handles.  An example is the "xCenter" property of `bounds` which is a cached derived property on the Bounds model.  It will not be returned by hasOwnProperty, but it ALSO can not be fetched with Immutable's `get()` function.  

It is still lame that we have to maintain our own version of `pluck` for immutable... because of little programming errors like this.

**Pull request merged**
