### PR TITLE
select dropdown is shifting

### PR DESCRIPTION
**Pull request by placegraphichere**
Addresses #2247.

### CODE REVIEW

**Comment by iwehrman** [comment]
Seems better, but it still bounces in at least the type face datalist:
type

**Comment by shaoshing** [comment]
that's a fancy magnifier.

**Comment by iwehrman** [comment]
I like it! http://xscopeapp.com/

**Comment by placegraphichere** [comment]
retina horizontal issue fixed back to @iwehrman

**Comment by iwehrman** [comment]
Works great! Except for the search bar :grimacing: 
search

**Comment by placegraphichere** [comment]
standard dropdowns as well as search and search-icons do not jump, hopefully back again for the last time

**Comment by iwehrman** [comment]
No luck :person_frowning: 
shift

**Comment by placegraphichere** [comment]
removed all rounding fixes for MQs in favor of a border with transparent fill on non-selected items

**Comment by iwehrman** [comment]
Like a rock.

**Pull request merged**
