### PR TITLE
Fix search bar colors in all color stops

### PR DESCRIPTION
**Pull request by DivyaPrabhakar**
References #3364 (@placegraphichere @iwehrman this might be of most interest to you guys) 

The most important parts of the PR I need approval on are: 

a.) The spacing and layout of the search bar now -- the positions of the search icon, the list icons, the category headers, and the search inquiry as the user is typing. 

For each color stop, check the colors of these with respect to the entire UI in that color stop: 
b.) The search icon
c.) The category headers
d.) The list icons
e.) The text after the list icons
f.) The ancestry text after each option 

As is, we are able to use the same less variable names for each of the items above, no matter the color stop. If changes are to be made to specific color stops, we will just need to add specific selectors targeting that color stop. Note -- Rest assured the blurriness is not actually how the searchbar is rendered, the images are weird for some reason.

### CODE REVIEW

**Comment by iwehrman** [comment]
Something ain't right:
image

That's in the no-doc UI.

**Comment by iwehrman** [comment]
The inner box is not centered in the outer box:
image

**Comment by iwehrman** [comment]
On retina, I think the left-edge-blue-highlight line is so small that it's hard to see:
image

**Comment by iwehrman** [comment]
Just a few additional suggestions. Looking good!

**Comment by iwehrman** [comment]
The borders still have different widths :scream:
Left: 
image

Right: 
image

Also, there's still a gap separating the blue highlight from the edge of the list in the lighter themes:
image

**Comment by DivyaPrabhakar** [comment]
@iwehrman 

I fixed the measurements to now be equal. 


As for the gap separation in the highlight, I am not seeing that on my machine.

**Comment by iwehrman** [comment]
Looks good!

**Pull request merged**
