### PR TITLE
Color for error iconz

### PR DESCRIPTION
**Pull request by placegraphichere**
- error icon color
- warning icon color
- fix for #2920

### CODE REVIEW

**Comment by iwehrman** [comment]
Review-only until we get a UIF exception.

**Comment by iwehrman** [comment]
What it looks like now:
image

**Comment by chadrolfs** [comment]
here's the other one updated: 
screen shot 2015-10-13 at 2 15 09 pm

**Comment by iwehrman** [comment]
Apparently we don't need a UIF exception for this because we're only changing the color of an icon. Hence, bombs away!

**Pull request merged**
