### PR TITLE
Increase contrast between primary and secondary search info

### PR DESCRIPTION
**Pull request by hamburge**
Adjust colors and sizes of search text to @placegraphichere's specifications (issue #1992)

### CODE REVIEW

**Comment by iwehrman** [comment]
Hmmm, I guess this is more of a complaint for @placegraphichere, but I think this is going the wrong direction. Here are before and after screenshots:

image

image

This mostly seems to make all of the text slightly smaller, which I think makes it harder to read. Personally I'd be going to opposite direction and making things bigger and with more contrast. What say you, @placegraphichere?

**Comment by iwehrman** [comment]
Re-assigning this to @DivyaPrabhakar. Figure out what to do!

**Comment by placegraphichere** [comment]
@DivyaPrabhakar try out https://github.com/adobe-photoshop/spaces-design/tree/sewalker/search-tweaks

**Comment by iwehrman** [comment]
I think that is an improvement.

**Comment by iwehrman** [comment]
Obviated by recent work by @DivyaPrabhakar.

**Pull request closed without merging**
