### PR TITLE
Don't fail resetBounds if the batchGet fails

### PR DESCRIPTION
**Pull request by volfied**
During shape edit / pen tool, `resetBounds` would fail if you pressed delete fast enough to delete all the points that layer would get deleted. We would try to `batchGet` bounds of a layer that doesn't exist.

Reset bounds is an updater, and I think it's ok for it to be failsafe.

Addresses #1191

### CODE REVIEW

**Comment by iwehrman** [comment]
I don't think this is the right place for there to be a blind catch. Instead, we should put the catch in whatever action is transferring to `resetBounds`. It's conceivable that this change is appropriate for _all_ callers of `resetBounds`, but that isn't clear to me at all. So, instead, I would try to keep this as localized as possible.

It would be great if there were some way for us to distinguish among the different error messages, so that the caller of `resetBounds` could test for a specific error and ignore just that one...

**Comment by volfied** [comment]
Problem is, this is not an action, it's an event handler (`"delete"`) that calls the action into the queue. So we can catch it around the action call, but controller also complains about an error and goes into the reset process.

**Comment by iwehrman** [comment]
A dumb way to solve that is just to make another action which transfers to to reset bounds and handles the error if appropriate.

**Comment by volfied** [comment]
@iwehrman Rebased with a new change, please review! I think it makes a lot of sense to call this function "quietly" during notification handlers, as they're not fast enough. After Shutdown Ian can look into making them more responsive :)

**Comment by iwehrman** [comment]
LGTM, thanks!

**Pull request merged**
