### PR TITLE
new intro for m3

### PR DESCRIPTION
**Pull request by placegraphichere**
~~Note: I'm getting a lintspaces error on a GIF ☓ src/img/first_launch/img_slide_toolset.gif~~
- string changes
- beginning of layout changes

- Ds logo
- icons
- replace bullets with titles
- Changed strings and content for the slides

- new images for a few slides
- icons for twitter and github
- string changes
- styling for a lot of it

- icon color tweaks

- removed unused images
- added new GIFs
- changed border-radius to be more reasonable
- renamed images
- removed selection slide

### CODE REVIEW

**Comment by mcilroyc** [comment]
@volfied did I hear you say you were going to restrict the lintspaces file set?

**Comment by volfied** [comment]
It's coming up.

**Comment by volfied** [comment]
@placegraphichere You'll need to rebase after #2626 hits.

**Comment by placegraphichere** [comment]
ok thanks @volfied

**Pull request merged**
