### PR TITLE
[Armchair designer] UI transparency

### PR DESCRIPTION
**Pull request by iwehrman**
This reintroduces a slight (3%) transparency to the UI, including the toolbar, header, and properties panel. It looks like this:
transparency

It correctly maintains full opacity for all the dialogs, like the color picker and search bar.

Addresses #1978. See in particular @DivyaPrabhakar's [recent note](https://github.com/adobe-photoshop/spaces-design/issues/1978#issuecomment-129993462).

Over to @designedbyscience and @placegraphichere for discussion.

### CODE REVIEW

**Comment by iwehrman** [comment]
yes

**Comment by designedbyscience** [comment]
I'll bother @placegraphichere about this today. I think maybe 2% just to reduce the noise a little further (I know, obnoxious)

**Comment by iwehrman** [comment]
Commit amended with 2% transparency. Now it looks like this:
image

**Comment by iwehrman** [comment]
yes

**Comment by iwehrman** [comment]
Rebased after #2115, but the at least the search bar is no longer fully opaque like it should be. Can you help, @placegraphichere?

**Comment by placegraphichere** [comment]
Both @davealonzo and I don't think this what we should do. It can look ok at times, but we just don't think it provides the clarity the UI needs at all times. Sorry @iwehrman

**Pull request closed without merging**
