### PR TITLE
remove menu item for vector mask editing.

### PR DESCRIPTION
**Pull request by pineapplespatula**

### CODE REVIEW

**Comment by volfied** [comment]
What about shortcuts-mac and shortcuts-win.json files?

**Comment by pineapplespatula** [comment]
@iwehrman  said not to worry about the strings and their localizations for MAX

**Comment by pineapplespatula** [comment]
@iwehrman  is this what you meant, or did you just mean the non root languages?

**Comment by iwehrman** [comment]
Well, I meant that you could leave all the strings in there. You removed one string, but not others. I guess I'd either remove none of them or all of them?

**Comment by pineapplespatula** [comment]
ok, they are all ripped out now

**Comment by iwehrman** [comment]
LGTM.

**Pull request merged**
