### PR TITLE
quick fix for reoder bug

### PR DESCRIPTION
**Pull request by pineapplespatula**

### CODE REVIEW

**Comment by mcilroyc** [comment]
this doesn't seem to work?  Either way I think it is preferred to use `transfer` instead of calling a *Command directly, and this is addressed in my forthcoming PR.

**Comment by mcilroyc** [comment]
closer.  still doesn't work, nor does it grunt correctly.

**Comment by pineapplespatula** [comment]
its working for me. do you still get the same error in this branch?

**Comment by mcilroyc** [comment]
I think you just needed: `this.transfer(getLayerOrderCommand, document)`  ... but anyway see my PR 1593

**Pull request closed without merging**
