### PR TITLE
make datalists update based on the model

### PR DESCRIPTION
**Pull request by pineapplespatula**
Ian is concerned about the model getting out of sync within the data list and our selection jumping around here. so i'm sending this over to him to verify if his concerns are well founded.

### CODE REVIEW

**Comment by iwehrman** [comment]
Indeed, this seems just fine. I'd like @hamburge to take a look too and make sure it works correctly with her search bar. Assigning @hamburge to review and merge.

**Comment by pineapplespatula** [comment]
this addresses issue https://github.com/adobe-photoshop/spaces-design/issues/1823

**Comment by iwehrman** [comment]
@hamburge: if you merge this, please mark the original issue FBNC and assign it back to the original filer to verify and close.

**Comment by hamburge** [comment]
Looks good!

**Pull request merged**
