### PR TITLE
Fine tune the document header resizing behavior

### PR DESCRIPTION
**Pull request by shaoshing**
This is related to issue #2558. Taki is not happy that the document header got shrinked in the middle. He is wondering if it is possible to trigger the shrinking only when the container is out of space. I couldn't come up with a easy solution for this (it requires some extra work to detect if whether or not the header will be out of space), so I adjusted its behavior to use smaller text when reach maximum header count, where the count is dynamically calculated based on the current width of the container. This looks good to me, at least the user won't be surprised that the text is shrinked in the middle.

Here is the before and after comparision: 

#### Before

tabs-resizing

#### After

new-tabs-resizing

### CODE REVIEW

**Comment by shaoshing** [comment]
Added discussion label so we can compare different shrink strategy.

**Comment by shaoshing** [comment]
Eric pointed out that this is not working well in non-retina screen, so I tried a different way to address both. I render two tab containers. one of them is invisible to the users and always using regualr tab size. Then I detect whether it has enough room to show all title completely. If not, then I re-render the second tab container in small tab size. This seems nicely fix the problem.

#### OSX

new-tabs2

#### WIN

new-tabs-win

**Comment by shaoshing** [comment]
This is ready for merging if Erice approve the implementation using a invisible tab container and is happy about the result. :D

**Comment by designedbyscience** [comment]
So Much Better.

**Pull request merged**
