### PR TITLE
Make sure document tab bar shrinks to fit export button

### PR DESCRIPTION
**Pull request by designedbyscience**
2 bugs, 1 stone

Addresses #2620 and #2659

### CODE REVIEW

**Comment by mcilroyc** [comment]
hovering over the tab makes the tab full-sized, and it seems a bit spastic to me.

**Comment by mcilroyc** [comment]
just to be more clear, here is an example vid of the effect I'm arguing against:
http://cl.ly/0x3n2m1P2C2B
I'm going to assign back to @designedbyscience to force him to answer for this, or tell me to shut up in public.

**Comment by designedbyscience** [comment]
I am restoring previous intended behavior that was lost in some Exports work. There is a lot of utility to seeing the whole filename in the tab (there is much than could be done better in the title bar, but I _think_ that making this less spastic is a fair amount of work)

Shut up @mcilroyc :lemon:

**Comment by mcilroyc** [comment]
#shuttinup

**Pull request merged**
