### PR TITLE
copy/paste: set text color by fill color, if style is not copied from text layer.

### PR DESCRIPTION
**Pull request by shaoshing**
Addresses issue #3134 . 

Also fixed bugs related to out of sycn between `Text#firstCharacterStyle` and `Text#characterStyle`: after updating text style (size, color, tracking), clicking copy button will copy the out-dated style.

### CODE REVIEW

**Comment by shaoshing** [comment]
I also tested copy/paste between text layer, vector layer, and graphic layer (only has blend mode and opacity attributes), and they are all working correctly now

**Comment by pineapplespatula** [comment]
@shaoshing  this doesnt seem to replace the opacity or the text color

**Comment by iwehrman** [comment]
I'm seeing it replace the color both directions. What are your repro steps to fail to catch teh color?

**Comment by iwehrman** [comment]
I'm seeing it replace opacity too.

**Comment by DivyaPrabhakar** [comment]
I'm with Ian -- I am seeing it replace opacity, color and size when it is copied from one text layer to another. When copying from type to vector, it copies color and opacity. The only thing not copied is the effects but I don't think it is supposed to copy effects.

**Comment by pineapplespatula** [comment]
it only copies layer opacity. not fill color opacity ( which is because text layers only have layer opacity and not fill opacity), 
but we can defer that bug for now

**Pull request merged**
