### PR TITLE
Text Alert Icons

### PR DESCRIPTION
**Pull request by placegraphichere**
- add string for tooltip warning - missing font and reflow
- textWarningLevel changes
- final color choice
- remove color for reflow text, keeps icon tho
- fix for #2122

### CODE REVIEW

**Comment by placegraphichere** [comment]
try again @iwehrman

**Comment by iwehrman** [comment]
Review-only while I figure out whether we need a UIF exception for this. I might ask you to rip out the tooltip changes if that eases concerns about UIF exceptions.

**Comment by iwehrman** [comment]
Indeed: I ask that this PR be split in two. One PR, which I'll merge now, should just update the icon color. The other, which I'll merge later, will update the tooltip strings.

**Comment by placegraphichere** [comment]
strings removed @iwehrman

**Pull request merged**
