### PR TITLE
Use REMs to draw sampler overlay and artboard adders

### PR DESCRIPTION
**Pull request by volfied**
Addresses https://github.com/adobe-photoshop/spaces-design/issues/2196

That's me in the sampler
That's me in the artboards

@iwehrman please review

### CODE REVIEW

**Comment by designedbyscience** [comment]
:100:

**Comment by iwehrman** [comment]
I like this, but can we push the multiplication into a helper function like `pxToRem`?

**Comment by volfied** [comment]
OK @iwehrman, made the change.

**Comment by iwehrman** [comment]
Radical.

**Pull request merged**
