### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by fzhu1978**
1. Latest translation.
2. Sync shortcuts files from English.

### CODE REVIEW

**Comment by fzhu1978** [comment]
@volfied 
Hi Barkin, please help to review and merge. Thanks.

**Comment by chadrolfs** [comment]
@fzhu1978 Barkin is out on sabbatical, re-assigning to Ian.

**Comment by iwehrman** [comment]
This looks good to me. @ktaki, would you please do some light testing on this branch? If it looks OK, please merge.

**Comment by ktaki** [comment]
Tested language switching to J, F, and G.

**Pull request merged**
