### PR TITLE
Sewalker/icons more sharper

### PR DESCRIPTION
**Pull request by placegraphichere**
Almost all current icons have been refreshed as well as their LESS size and position information if that was necessary.

### CODE REVIEW

**Comment by designedbyscience** [comment]
Noticed couple things, probably from my merge:
untitled-9___48_5___group_1__rgb_8____

Is the Not Visible icon supposed to be bigger?
And, the colors got messed up there for the selected state

**Comment by placegraphichere** [comment]
Addressed both of these comments
- Is the Not Visible icon supposed to be bigger?
- And, the colors got messed up there for the selected state

**Comment by iwehrman** [comment]
image

**Comment by placegraphichere** [comment]
tumblr_inline_ns4ch2aofc1r1fj7r_250

**Comment by shaoshing** [comment]
shiny

**Comment by designedbyscience** [comment]
These look great

**Pull request merged**
