### PR TITLE
Only update overlays when pointer is inside canvas bounds

### PR DESCRIPTION
**Pull request by iwehrman**
What it says! This cuts down on some pointless, wasteful calls to `hitTest`.

Addresses #3732.

### CODE REVIEW

**Comment by volfied** [comment]
This only works for top and left areas of the window. I mean, it's still better than calling it all the time, but we should instead check with panel store to avoid making calls when mouse pointer is out of the visible canvas.

**Comment by iwehrman** [comment]
Derp. I'll try again.

**Comment by iwehrman** [comment]
OK, let's try again! Now I'm checking against the canvas bounds from the panel store. And on all four sides! :sweat_smile:

**Comment by iwehrman** [comment]
But, really, who even moves their mouse that far to the right anyway?

**Comment by shaoshing** [comment]
Verified all four sides. Thanks for fixing!

**Pull request merged**
