### PR TITLE
Moved the dirty document indicator and changed the color to red

### PR DESCRIPTION
**Pull request by DivyaPrabhakar**
Regarding issue #2842 

Now looks like:

### CODE REVIEW

**Comment by designedbyscience** [comment]
Could you add some space between that and the document name? Very smushed together right now

**Comment by DivyaPrabhakar** [comment]
@designedbyscience How is this?
alt text

**Comment by designedbyscience** [comment]
Yea that's better

**Comment by designedbyscience** [comment]
Great

**Pull request merged**
