### PR TITLE
Restore policies after nativePaste only if not currently in modal tool state

### PR DESCRIPTION
**Pull request by mcilroyc**
…by toolModalStateChanged - even though those are received only at the end of modal placement.

The theory is that, as a workaround for the un-timely toolModalStateChanged events, we must suspend policies at the beginning of nativePaste.  But, because we DO end up receiving toolModalStateChanged (both enter and exist, in quick succession) after the user places the object, then we do not strictly need to restore policies "finally" as part of nativePaste.

This hopes to address #3126 which was restoring policies while still in text edit modal state.

### CODE REVIEW

**Comment by iwehrman** [comment]
Can you sprinkle a comment about this in here along the lines of "This looks like a bug because we aren't restoring policies, but it isn't because...."

**Comment by mcilroyc** [comment]
comment elaborated, commit amended.

**Comment by pineapplespatula** [comment]
the code for this looks fine, but i would like to wait for approval by @chadrolfs or @ktaki

**Comment by iwehrman** [comment]
This fails when attempting to paste text into the PS canvas (not in a modal tool state).

**Comment by iwehrman** [comment]
Pasting an image copied from a web page also fails in a slightly different way.

**Comment by ktaki** [comment]
"This fails when attempting to paste text into the PS canvas (not in a modal tool state)." After this, the shortcut keys for the tools selects tools for standard Ps.

**Comment by iwehrman** [comment]
I think this is the fix we want to go with for M3. It works for me so far.

**Comment by iwehrman** [comment]
For posterity, I'll note that we have to suspend policies in `nativePaste` in the first place due to this core bug: 
[https://watsonexp.corp.adobe.com/#bug=4074688](https://watsonexp.corp.adobe.com/#bug=4074688)

**Comment by pineapplespatula** [comment]
this should be rebased to 1 PR

**Comment by mcilroyc** [comment]
re-ba-ba-based

**Comment by iwehrman** [comment]
Cross your fingers.

**Pull request merged**
