### PR TITLE
Sampling layer effects should delete extra effects.

### PR DESCRIPTION
**Pull request by shaoshing**
Prevously, sampling layer effects only handle the following cases:

1. delete all effects if the target has no layer effect
2. copy existing effects from source layer to target layer

This PR handles the 3rd case:

3. If target layer has more effects then the source layer, it should duplicate the existed effects from the source layer, and delete the extra effects.

Addresses #3016

### CODE REVIEW

**Comment by chadrolfs** [comment]
@shaoshing does this PR also cover cases for copy/paste ( not covered in PR #3045 )?

**Comment by iwehrman** [comment]
This works, but when I undo I see a number of different history states, as though the effects are being deleted/replace one at at time:
img

**Comment by shaoshing** [comment]
This one is probably fixed in https://github.com/adobe-photoshop/spaces-design/pull/3062. but I will double check with that fix in this PR

**Comment by shaoshing** [comment]
@iwehrman confirmed that it is fixed by #3062

**Comment by shaoshing** [comment]
Rebased master with the history state fix, @iwehrman you should be able to undo the sampler effects now.

**Comment by iwehrman** [comment]
OK! Looks great.

**Pull request merged**
