### PR TITLE
Mask Layer Icons

### PR DESCRIPTION
**Pull request by placegraphichere**
#2668 
- mask icons for all mask-able and Ds compatible layer types:
  - text
  - image
  - smart object
  - linked smart object
  - cloud smart object
  - folder open/close
- refreshed icons for folder that open to the right, from customer
feedback awhile ago
- adjustment layer mask icon #2671

### CODE REVIEW

**Comment by pineapplespatula** [comment]
do we need a "co-layer-cloud-linked-alert-mask" icon?

**Comment by pineapplespatula** [comment]
@placegraphichere  : one question

**Comment by pineapplespatula** [comment]
also we need an artboard-mask icon

**Comment by pineapplespatula** [comment]
(on a happy note the new icons look great)

**Comment by placegraphichere** [comment]
I con all the icons, back to @pineapplespatula

**Comment by pineapplespatula** [comment]
LGTM

**Pull request merged**
