### PR TITLE
Show sampler HUD on shift+click instead of spacebar

### PR DESCRIPTION
**Pull request by volfied**
Implements enhancement #2471. Wrote this out for @placegraphichere to test and get the feel of it.

### CODE REVIEW

**Comment by iwehrman** [comment]
We're abandoning the spacebar shortcut??

**Comment by volfied** [comment]
I believe so, this is to get a feel for cmd+shift+click. People except space to be a pan at all times.

**Comment by chadrolfs** [comment]
:cry: Space makes it so easy.  Cmd + Shift + click makes it feel more clunky and less easy to access.

**Comment by volfied** [comment]
Updated this to be shift+click, since shift+click was FX, and it's available in the HUD as well. Please test and tell me about your experience here

**Comment by iwehrman** [comment]
I prefer the spacebar shortcut because it works without having to click with a tool. I'd like to use the same shortcut with the vector mask create-mask-with-shape HUD, and I'm not sure shift-click really works there?

**Comment by chadrolfs** [comment]
Issues:  
- Space pan doesn't work
- Sampling Type only samples Typeface (doesn't include color/align/size)

**Comment by volfied** [comment]
Closing this as we've decided to stay with spacebar.

**Pull request closed without merging**
