### PR TITLE
Clear stored modifier state when the application becomes inactive

### PR DESCRIPTION
**Pull request by iwehrman**
We currently store modifier state from the `adapterFlagsChanged` os event so that click handlers can determine which modifiers were active during the click. However, we only get `adapterFlagsChanged` events when the application is active. So, e.g., if you cmd-tab away from Design Space, we store modifier state with the command modifier enabled, but if you then click the title bar to activate the application again, no new `adapterFlagsChanged` events are emitted, and so the stored modifier state is now stale and the next click event will turn into a command click.

This works around the problem by clearing the modifier state whenever the application becomes inactive. As noted in the comment below, the adapter would ideally also emit an `adapterFlagsChanged` event whenever the application becomes active so that our state can be immediately brought up to date. It doesn't currently, however, but the remaining bug (i.e., if you hold command down, activate the application and click, expecting a command click but getting only a modifier-free click) seems much less severe. (Watson bug for the core request coming soon.)

Addresses #2946.

### CODE REVIEW

**Comment by iwehrman** [comment]
Associated core bug: https://watsonexp.corp.adobe.com/#bug=4074645

**Comment by pineapplespatula** [comment]
LGTM

**Comment by jsbache** [comment]
Edge case. Let's defer

**Comment by jsbache** [comment]
Why does DS cache the modifier flags. Modifiers should be available on the mouse-down commands. This is the bast (only) way to get event synchronized information

**Comment by iwehrman** [comment]
@jsbache: the problem is that our event handlers are associated with particular DOM nodes, and so we rely on browser events to trigger operations like this instead of adapter events, which are disconnected from any particular DOM node.

**Comment by iwehrman** [comment]
(Also, I think the last time I checked this information was not making it into the browser events, but I should probably verify that again.)

**Comment by jsbache** [comment]
I am closing the Watson. Please create a jira issue if you don't get modifier keys on mouse events

**Pull request merged**
