### PR TITLE
Language specific positioning within the intro dialog 

### PR DESCRIPTION
**Pull request by DivyaPrabhakar**
1. Fixes the positioning of the "Continue" button in Japanese, German and French on the first screen of the welcome dialog. (References #2960)

2. Adjusted the line widths of the paragraph of on the first screen of the welcome dialog in Japanese and German to avoid orphans.

3. Changed sentences in the Japanese welcome screens because the phrasing was awkward. @ktaki make sure that these are now correct. 

4. Changed the color of hover states of the social media buttons. @placegraphichere said that he is going to make the color difference between @item/@icon-active and @item/@icon-hover more noticeable and when he does, it will already be in effect in the Welcome screen. (For testing purposes before the color change is made by Seth, the Twitter icon shows the hover state most clearly right now.)

**Japanese** 

___Welcome Screen___

___Toolset___

___Search___

___Sampler___

___Artboards___

___Swap___

___Switching back to Photoshop___

**German** 

___Welcome Screen___

___Tooltip___

___Search___

___Sampler___

___Artboards___

___Swap___

___Switching to Photoshop___

### CODE REVIEW

**Comment by iwehrman** [comment]
Does the second sentence need a hard break right after the first? In German and Japanese, it looks pretty weird the way there's only a single word on the second line...

**Comment by DivyaPrabhakar** [comment]
@iwehrman I am not sure about that, I didn't touch any of the writing or header tags I just changed the positioning of the button. I can make the width of the header tags smaller for other languages to distribute the words more evenly if that helps?

**Comment by ktaki** [comment]
I only can speak for Japanese, but remove the hard break after the first line. Make it one paragraph with left justified. Center justification does not work for Japanese. Make this change for all other screens. Also all screens other than the first, the images and descriptions are shifted to up. The descriptions are too close to the upper edge. Bring them down.

**Comment by DivyaPrabhakar** [comment]
@ktaki Just as a reminder of what we talked about today -- I put in the translated strings you gave me and you said you would check with the i18n team about whether these changes would be overwritten or not.

**Comment by ktaki** [comment]
Yes, I will follow up on that.

**Comment by ktaki** [comment]
@DivyaPrabhakar  as per a email conversation with Feng Zhu, please send him the translation changes to Feng. Thanks!

**Comment by ktaki** [comment]
@DivyaPrabhakar Do you know which font is used for each language in the intro?

**Comment by DivyaPrabhakar** [comment]
@ktaki I think it is Adobe Clean. @placegraphichere  can you verify?

**Comment by placegraphichere** [comment]
Yes Adobe Clean

**Comment by iwehrman** [comment]
Better!

**Pull request merged**
